name: stringer
description: A class that manipulates Strings
version: 1.0.1
publish_to: "none"
homepage: https://github.com/RagehAz/Stringer.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  clipboard: ^0.1.3
  intl: ^0.17.0

  numeric:
    git:
      url: https://github.com/RagehAz/numeric.git
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0


flutter:
